Monitoring: Fix runtime errors when monitoring Dataset Metadata
mrmap-community/mrmap pull request #179
Opened 2021-09-15 09:54 UTC by MrSnyder

This fixes runtime errors when monitoring Dataset Metadata instances.

2021-09-16 14:52 UTC, jokiefer requested changes
see comment

2021-09-16 14:52 UTC, jokiefer commented on mrmap/monitoring/monitoring.py
This should be better places as an utility function in resourceNew app.

2021-09-16 14:53 UTC, jokiefer requested changes
see comment

2021-09-16 14:53 UTC, jokiefer commented on mrmap/monitoring/monitoring.py
> +    def _get_session_for_request(self):
This should be better places as an utility function in resourceNew app.

2021-11-02 14:47 UTC, MrSnyder reviewed
LGTM, however after @jokiefer comment I am a bit unsure if `monitoring.py` is the best place for `_get_session_for_request`.

2021-11-02 14:47 UTC, MrSnyder commented on mrmap/locale/de/LC_MESSAGES/django.po
>  msgstr "Einzelheiten"
"Einzelheiten" is a rather uncommon word in German, probably better: "Details"

2021-11-03 07:56 UTC, Unraveler commented on mrmap/locale/de/LC_MESSAGES/django.po
>  msgstr "Einzelheiten"
```suggestion
msgstr "Details"
```

2021-11-03 08:15 UTC, merged